name: Build and Deploy to Github Pages

on:
  push:
    branches:
      - master  # Change if your branch is different

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Use GitHub Actions' cache to cache dependencies
      - uses: actions/cache@v3
        with:
          path: |
            vendor/bundle
          key: ${{ runner.os }}-cache-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-cache-

      # Install Ruby, Bundler, and Jekyll dependencies
      - name: Install Ruby and Bundler
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby-full
          gem install bundler
          bundle install

      # Use GitHub Deploy Action to build and deploy Jekyll
      - uses: jeffreytse/jekyll-deploy-action@v0.6.0
        with:
          provider: 'github'
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'gh-pages'
          jekyll_src: './'
          jekyll_cfg: '_config.yml'
          jekyll_baseurl: ''
          bundler_ver: '>=0'
          cname: ''
          actor: ''
          pre_build_commands: 'bundle install'
