name: Build and Deploy to Github Pages

on:
  push:
    branches:
      - master  # Change if your branch is different

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Cache Ruby Gems
      - name: Cache Gems
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      # Install Ruby using setup-ruby action
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2  # Ensure compatibility with GitHub Actions
          bundler-cache: true # Caches gems automatically

      # Install Dependencies
      - name: Install Bundler and Jekyll
        run: bundle install --jobs 4 --retry 3

      # Remove Old Bundler Cache to Avoid Conflicts
      #- name: Remove old Bundler cache
      #  run: rm -rf vendor/bundle .bundle

      # Disable Bundler Frozen Mode
      - name: Disable Bundler Frozen Mode
        run: bundle config set frozen false

      # Deploy Jekyll Site
      - name: Deploy Jekyll Site
        uses: jeffreytse/jekyll-deploy-action@v0.6.0
        with:
          provider: 'github'
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'gh-pages'
          jekyll_src: './'
          jekyll_cfg: '_config.yml'
          jekyll_baseurl: ''
          bundler_ver: '>=0'
          cname: ''
          actor: ''
          pre_build_commands: 'bundle install'
